import pickle
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import euclidean_distances
import time

def load_feature_db(filepath="features/image_features.pkl"):
    """
    Loads the feature database generated by Person 1.
    """
    with open(filepath, 'rb') as f:
        data = pickle.load(f)
    return data

def search_cosine(query_vec, feature_db, top_k=5):
    """
    Finds top-K matches using Cosine Similarity (Higher is better).
    """
    all_vectors = np.array(list(feature_db.values()))
    filenames = list(feature_db.keys())
    
    query_vec = query_vec.reshape(1, -1)
    
    # Calculate similarity scores (1.0 = identical)
    start_time = time.time()
    scores = cosine_similarity(query_vec, all_vectors).flatten()
    search_time = time.time() - start_time
    
    # Sort descending (best to worst)
    indices = np.argsort(scores)[::-1][:top_k]
    
    results = [(filenames[i], scores[i]) for i in indices]
    return results, search_time

def search_euclidean(query_vec, feature_db, top_k=5):
    """
    Finds top-K matches using Euclidean Distance (Lower is better).
    """
    all_vectors = np.array(list(feature_db.values()))
    filenames = list(feature_db.keys())
    
    query_vec = query_vec.reshape(1, -1)
    
    # Calculate straight-line distance (0.0 = identical)
    start_time = time.time()
    distances = euclidean_distances(query_vec, all_vectors).flatten()
    search_time = time.time() - start_time
    
    # Sort ascending (closest to farthest)
    indices = np.argsort(distances)[:top_k]
    
    results = [(filenames[i], distances[i]) for i in indices]
    return results, search_time

if __name__ == "__main__":
    # 1. Load the database
    try:
        db = load_feature_db()
        print(f"--- Person 2: System Ready ---")
        print(f"Loaded {len(db)} image features from the database.")
    except Exception as e:
        print(f"Error loading database: {e}")
        exit()

    # 2. Setup a Test Query (Using an existing image as a 'fake' user upload)
    test_image_name = list(db.keys())[0]
    test_query_vec = db[test_image_name]
    print(f"\nSimulating search for Query Image: {test_image_name}")

    # 3. Perform Cosine Search
    cosine_results, c_time = search_cosine(test_query_vec, db)
    print(f"\n[Cosine Similarity] Search took {c_time:.6f}s")
    for i, (name, score) in enumerate(cosine_results):
        print(f"{i+1}. {name} | Similarity: {score:.4f}")

    # 4. Perform Euclidean Search
    euclidean_results, e_time = search_euclidean(test_query_vec, db)
    print(f"\n[Euclidean Distance] Search took {e_time:.6f}s")
    for i, (name, dist) in enumerate(euclidean_results):
        print(f"{i+1}. {name} | Distance: {dist:.4f}")

    # 5. Summary for Person 2's Report
    print("\n--- Final Conclusion for Group ---")
    if cosine_results[0][0] == euclidean_results[0][0]:
        print("Both metrics correctly identified the top match.")
    else:
        print("Metrics disagree on the best match. Compare visual results in the notebook.")